### ISSUE TITLE
Allow equal "from" and "to" IORs in glass BRDF

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#989] opened 2016-03-30 19:31 UTC
There is a discontinuity in the formula used by the glass BRDF when the "from" and "to" IOR are equal, but everything works fine around that discontinuity. The discontinuity should be plugged to prevent surprising, seemingly broken results.

**Comment by est77** [comment] 2017-12-08 15:31
Duplicate of #1756

**Closed by est77** 2017-12-08 15:31 UTC
Labels: Bug
