### ISSUE TITLE
OSL shaders such as as_disney_material shouldn't limit bounces by default

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2322] opened 2018-11-27 08:55 UTC
The global bounce limits should prevail by default.

**Comment by luisbarrancos** [comment] 2018-11-28 04:32
@dictoon we always provide a override to the maximum number of bounces in the material shaders since the user might want to for instance, limit the number of bounces allowed for a refractive sphere in a particular setup, while having other spheres with lower/higher bounces. That was a conscious choice. Do you want to remove this feature from the materials? If so, they need to be hidden and not removed in order not to break backwards compat. If the problem is having a default number of bounces, perhaps we can instead increase the default value to a more convenient number. Suggestions?

**Comment by dictoon** [comment] 2018-11-28 07:31
I'm totally fine with providing overrides for the maximum number of bounces in materials. The point is that by default, that override should be _disabled_. Setting it to a large enough value (100) seems fine.

**Comment by dictoon** [comment] 2018-11-28 07:32
This applies to all materials and to all overrides for global settings.

**Comment by luisbarrancos** [comment] 2018-12-23 05:30
Addressed in https://github.com/appleseedhq/appleseed/pull/2348

**Closed** 2018-12-26 22:35 UTC
Labels: appleseed.shaders
