### ISSUE TITLE
Fix accumulation of passes rendering percentage

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2198] opened 2018-09-16 08:46 UTC
```
 --- beginning rendering pass 1 ---
 rendering, 25.0% done
 rendering, 50.0% done
 rendering, 75.0% done
 rendering, 100.0% done
 wrote checkpoint for pass 1.
 --- beginning rendering pass 2 ---
 rendering, 125.0% done
 rendering, 150.0% done
 rendering, 175.0% done
 rendering, 200.0% done
 wrote checkpoint for pass 2.
 --- beginning rendering pass 3 ---
 rendering, 225.0% done
 rendering, 250.0% done
 rendering, 275.0% done
 rendering, 300.0% done
 wrote checkpoint for pass 3.
 --- beginning rendering pass 4 ---
 rendering, 325.0% done
 rendering, 350.0% done
 rendering, 375.0% done
 rendering, 400.0% done
 wrote checkpoint for pass 4.
 --- beginning rendering pass 5 ---
 rendering, 425.0% done
 rendering, 450.0% done
 rendering, 475.0% done
 rendering, 500.0% done
 wrote checkpoint for pass 5.
 --- beginning rendering pass 6 ---
 rendering, 525.0% done
 rendering, 550.0% done
 rendering, 575.0% done


```

It should be between 0 and 100%.

**Comment by dictoon** [comment] 2018-09-16 10:50
Duplicate of #864.

**Closed by dictoon** 2018-09-16 10:50 UTC
Labels: Bug, Good First Issue
