### ISSUE TITLE
Harsh boundaries with bump mapping + IBL

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1767] opened 2017-12-09 10:14 UTC
Repro case:
https://www.dropbox.com/s/lxao8aplfcatjs0/bump_test_scene.zip?dl=0

Render:
![image](https://user-images.githubusercontent.com/321290/33794741-15df315a-dcd2-11e7-974b-eefd60104a0e.png)

**Comment by luisbarrancos** [comment] 2017-12-09 14:43
As discussed, i think we can close it, i cannot reproduce it with 1.8.0.

**Closed by luisbarrancos** 2017-12-09 14:43 UTC
Labels: Bug
