### ISSUE TITLE
Qt resets locale when loading images

### ISSUE THREAD

**Issue by gospodnetic** [appleseedhq/appleseed#1435] opened 2017-06-02 14:18 UTC
* Open a project (I used `test scenes/bsdf/metalbrdf/01 - metalbrdf.appleseed`)
* Choose `File>Save Project As...`
* Try to reload or open the project which was just created
Reloading or loading fails with error message

```
2017-06-02T14:08:08.702521Z <020>   333 MB error   | invalid vector format.
2017-06-02T14:08:08.702554Z <020>   333 MB error   | while defining <matrix> element: expected 16 scalar coefficients, got 0.
...
```

**Comment by dictoon** [comment] 2017-06-03 16:52
Confirmed to be a locale problem: while the locale is properly set to `C` in `main()`, it ends up being

    LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8

by the time we reach `ProjectFileWriter::write_plain_project_file()`.

**Comment by gospodnetic** [comment] 2017-06-05 16:07
QT changes locale when loading image from disk for the very first time. The problem was tracked in both QImage and QPixmap classes. Both classes in their `load()` function call `QImageReader.read()`  which results in change of the locale back to system settings.

A dirty fix is to load any image at the very beginning of the main and reset the locale right after, thus preventing the `QImageReader.read()` to change it again (as it happens only on the very first `read`).

In appleseed.studio code the locale change occurs in `miscellaneous.cpp`,`load_icons()`, line 170.

**Comment by dictoon** [comment] 2017-06-15 09:44
By grepping for `std::setlocale()` though Qt 4.8.7, zlib and libpng source code, none of them appears to permanently set the C standard library locale.

Unless you can pinpoint exactly where in Qt is the locale changed, we're unlikely to be able to fix this bug.

**Comment by dictoon** [comment] 2017-06-15 09:49
A better workaround would be to simply save then restore the locale in `appleseed::studio::load_icons()` since this is the only place where we actually load images with Qt.

**Comment by dictoon** [comment] 2017-06-15 09:52
> The problem was tracked in both QImage and QPixmap classes

@gospodnetic How did you track this, and where do we use `QImage` to load images?

**Comment by gospodnetic** [comment] 2017-06-15 09:55
We use QPixmap which internally uses QImage and QImageReader

**Comment by dictoon** [comment] 2017-06-15 10:03
Right, just found out :) Thanks.

**Comment by dictoon** [comment] 2017-07-10 20:25
Closing this as a (somewhat hacky, admittedly) solution has been found

**Closed by dictoon** 2017-07-10 20:25 UTC
Labels: appleseed.studio, Bug, Easy
